apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJRV3hsZUMxQ1pYUmhPbWRwZEdoMVlsOXdZWFJmTVRGQlVGQlJURTVCTUhoWVNFbDJZMlJXWVhoWVlsOUtXWEJOZEZkTWVUUk9hM1ZqWW1KV1lqVTFSRVJvVG1OUGFrbHpZMFU1WmxGV2NFaGpaVEJ6VEZSNVF6VXlNelpOVjFCdk1teDNUWE5pYWc9PSINCiAgICB9DQogIH0NCn0NCg==
type: kubernetes.io/dockerconfigjson
