apiVersion: v1
kind: Secret
metadata:
  name: cinemaabyss-secrets
  namespace: cinemaabyss
type: Opaque
data:
  # Base64 encoded values
  # echo -n "postgres_password" | base64
  DB_PASSWORD: cG9zdGdyZXNfcGFzc3dvcmQ=
  .dockerconfigjson: ew0KICAiYXV0aHMiOiB7DQogICAgImdoY3IuaW8iOiB7DQogICAgICAiYXV0aCI6ICJRV3hsZUMxQ1pYUmhPbWRwZEdoMVlsOXdZWFJmTVRGQlVGQlJURTVCTUhoWVNFbDJZMlJXWVhoWVlsOUtXWEJOZEZkTWVUUk9hM1ZqXG5ZbUpXWWpVMVJFUm9UbU5QYWtselkwVTVabEZXY0VoalpUQnpURlI1UXpVeU16Wk5WMUJ2TW14M1RYTmlhZz09Ig0KICAgIH0NCiAgfQ0KfQ0K==
