{{- if .Values.proxyService.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  replicas: {{ .Values.proxyService.replicas }}
  selector:
    matchLabels:
      app: proxy-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: proxy-service
    spec:
      containers:
        - name: proxy-service
          image: ghcr.io/alex-beta/yandex_architecture_sprint2/proxy-service:sha-f0aa717
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8000"
            - name: MONOLITH_URL
              value: "http://monolith:8080"
            - name: MOVIES_SERVICE_URL
              value: "http://movies-service:8081"
            - name: EVENTS_SERVICE_URL
              value: "http://events-service:8082"
            - name: GRADUAL_MIGRATION
              value: "true"
            - name: MOVIES_MIGRATION_PERCENT
              value: "50"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  namespace: {{ .Values.global.namespace }}
  labels:
    app: proxy-service
    app.kubernetes.io/name: {{ include "cinemaabyss.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: proxy-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8080
  type: ClusterIP
{{- end }}
